### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridis-com** [lumenitb/lumen-sdk#3]
void

**Comment by ceefour** [comment]
Currently everyone involved in Lumen are committers so this shouldn't be an
urgent issue.

In the future a solution would be a proper build of SDK distro, since this
is a source repository anyway. An SDK distro will combine all sources,
built binaries, documentation, and sample data for quick setup by a
developer. But for quite some time we won't have any external developer yet.

**Comment by lazaridis-com** [comment]
Congratulations. Your reply managed to totally demotivate me on making the planned contributions!

**Comment by ceefour** [comment]
Sorry. I'm not saying this issue isn't important, it is. But it's not
urgent in the sense not planned in the near term but on the long term.

**Comment by lazaridis-com** [comment]
@ceefour , can you please delete this issue?
